#!/usr/bin/env python3
"""Regenerate RESULTS.md from the result JSONs.

Numbers in the writeup are never typed by hand: this reads whatever
``results/`` contains and renders it.  Missing inputs produce an explicit
"not yet run" line rather than a gap, so it is always obvious which claims are
backed by a measurement.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = """# Results

Regenerated by `python scripts/summarize.py`. Do not edit by hand.

Chance floors and sample sizes are given for every table. Where a result is
negative or fails to support the hypothesis, it is reported here in the same
form as a positive one.
"""


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def section_ar(results: Path) -> str:
    d = _load(results / "sim_ar.json")
    if not d:
        return "## 1. Captioning ± referential alignment\n\n_Not yet run: `python scripts/run_simulation.py ar`._\n"
    rows = d["rows"]
    args = d.get("args", {})
    regimes = list(dict.fromkeys(r["regime"] for r in rows))
    conds = list(dict.fromkeys(r["condition"] for r in rows))
    out = [
        "## 1. Captioning ± referential alignment (controlled simulation)",
        "",
        f"Picture-vocabulary accuracy on **held-out exemplars**. Chance = 1/40 = 0.025. "
        f"{args.get('seeds','?')} seeds, {args.get('steps','?')} steps, "
        f"corpus = {args.get('corpus_size','?')} episodes.",
        "",
        "| condition | " + " | ".join(r.capitalize() for r in regimes) + " |",
        "|---|" + "---|" * len(regimes),
    ]
    for c in conds:
        cells = []
        for g in regimes:
            r = next((x for x in rows if x["regime"] == g and x["condition"] == c), None)
            cells.append(f"{r['acc_mean']:.3f} ± {r['acc_std']:.3f}" if r else "—")
        out.append(f"| {c} | " + " | ".join(cells) + " |")
    out += [
        "",
        "The regimes vary how much of the speech is non-referential, how often a word is "
        "uttered while its referent is absent, and how many never-named background objects "
        "are present.",
        "",
    ]
    return "\n".join(out)


def section_audit(results: Path) -> str:
    d = _load(results / "text_blind_audit.json")
    if not d:
        return "## 2. Text-blind benchmark audit\n\n_Not yet run: `python scripts/text_blind_audit.py --roots ...`._\n"
    out = [
        "## 2. Text-blind benchmark audit",
        "",
        "Accuracy of a training-free 32×32 luminance + RGB-histogram matcher that **never reads "
        "the prompt**. Wilson 95% intervals.",
        "",
        "| task | n | chance | most-frequent-answer | image-match (text-blind) |",
        "|---|---|---|---|---|",
    ]
    for task, r in sorted(d.items()):
        pos = f"{r['position_acc']:.2f} [{r['position_ci'][0]:.2f}, {r['position_ci'][1]:.2f}]"
        mat = (
            f"**{r['match_acc']:.2f}** [{r['match_ci'][0]:.2f}, {r['match_ci'][1]:.2f}] (n={r['match_n']})"
            if "match_acc" in r
            else "n/a"
        )
        out.append(f"| {task} | {r['n_items']} | {r['chance']:.2f} | {pos} | {mat} |")
    out += [
        "",
        "Tasks with no query image to match against show `n/a`; the matcher is inapplicable, "
        "not merely unsuccessful.",
        "",
    ]
    return "\n".join(out)


def section_efficiency(results: Path) -> str:
    d = _load(results / "sim_efficiency.json")
    if not d:
        return "## 3. Scope condition\n\n_Not yet run: `python scripts/run_simulation.py efficiency`._\n"
    rows = d["rows"]
    sizes = sorted({r["corpus_size"] for r in rows})
    conds = list(dict.fromkeys(r["condition"] for r in rows))
    out = [
        "## 3. Scope condition — the contrastive setting, where it does *not* help",
        "",
        "Lexicon accuracy vs. finite corpus size, contrastive objective. Reported because it is "
        "the boundary of the method's claim.",
        "",
        "| condition | " + " | ".join(f"n={s}" for s in sizes) + " |",
        "|---|" + "---|" * len(sizes),
    ]
    for c in conds:
        cells = []
        for s in sizes:
            r = next((x for x in rows if x["condition"] == c and x["corpus_size"] == s), None)
            cells.append(f"{r['acc_mean']:.3f}" if r else "—")
        out.append(f"| {c} | " + " | ".join(cells) + " |")
    out += [
        "",
        "No reliable benefit, and at large corpus sizes the exclusivity conditions are slightly "
        "worse. The batch-level InfoNCE draws negatives from the marginal and already suppresses "
        "hub collapse, so the column constraint has nothing left to fix.",
        "",
    ]
    return "\n".join(out)


def section_yusmith(results: Path) -> str:
    d = _load(results / "sim_yusmith.json")
    if not d:
        return "## 4. Yu & Smith (2007) psychometric fit\n\n_Not yet run: `python scripts/run_simulation.py yusmith`._\n"
    rows = d["rows"]
    best = min(rows, key=lambda r: r["rmse"])
    out = [
        "## 4. Yu & Smith (2007) psychometric fit",
        "",
        "An unconstrained ideal observer is at ceiling on the original design, so the question is "
        "what memory decay reproduces the human ordering with one shared free parameter.",
        "",
        "| memory decay γ | 2×2 | 3×3 | 4×4 | RMSE vs human |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        p = r["pred"]
        out.append(
            f"| {r['gamma']} | {p.get('2', float('nan')):.3f} | {p.get('3', float('nan')):.3f} | "
            f"{p.get('4', float('nan')):.3f} | {r['rmse']:.3f} |"
        )
    h = rows[0]["human"]
    out += [
        f"| **human** | {h['2']:.3f} | {h['3']:.3f} | {h['4']:.3f} | — |",
        "",
        f"Best fit at γ = {best['gamma']} (RMSE {best['rmse']:.3f}).",
        "",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", type=Path, default=Path("results"))
    ap.add_argument("--out", type=Path, default=Path("RESULTS.md"))
    args = ap.parse_args()
    text = "\n".join([
        HEADER,
        section_ar(args.results),
        section_audit(args.results),
        section_efficiency(args.results),
        section_yusmith(args.results),
    ])
    args.out.write_text(text)
    print(f"wrote {args.out} ({len(text)} chars)")


if __name__ == "__main__":
    main()
