#!/usr/bin/env python3
"""Regenerate RESULTS.md from the result JSONs.

Numbers in the writeup are never typed by hand: this reads whatever
``results/`` contains and renders it.  Missing inputs produce an explicit
"not yet run" line rather than a gap, so it is always obvious which claims are
backed by a measurement.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = """# Results

Regenerated by `python scripts/summarize.py`. Do not edit by hand.

Chance floors and sample sizes are given for every table. Where a result is
negative or fails to support the hypothesis, it is reported here in the same
form as a positive one.
"""


def _load(p: Path):
    return json.loads(p.read_text()) if p.exists() else None


def section_ar(results: Path) -> str:
    d = _load(results / "sim_ar.json")
    if not d:
        return "## 1. Captioning ± referential alignment\n\n_Not yet run: `python scripts/run_simulation.py ar`._\n"
    rows = d["rows"]
    args = d.get("args", {})
    regimes = list(dict.fromkeys(r["regime"] for r in rows))
    conds = list(dict.fromkeys(r["condition"] for r in rows))
    out = [
        "## 1. Captioning ± referential alignment (controlled simulation)",
        "",
        f"Picture-vocabulary accuracy on **held-out exemplars**. Chance = 1/40 = 0.025. "
        f"{args.get('seeds','?')} seeds, {args.get('steps','?')} steps, "
        f"corpus = {args.get('corpus_size','?')} episodes.",
        "",
        "| condition | " + " | ".join(r.capitalize() for r in regimes) + " |",
        "|---|" + "---|" * len(regimes),
    ]
    for c in conds:
        cells = []
        for g in regimes:
            r = next((x for x in rows if x["regime"] == g and x["condition"] == c), None)
            cells.append(f"{r['acc_mean']:.3f} ± {r['acc_std']:.3f}" if r else "—")
        out.append(f"| {c} | " + " | ".join(cells) + " |")
    out += [
        "",
        "The regimes vary how much of the speech is non-referential, how often a word is "
        "uttered while its referent is absent, and how many never-named background objects "
        "are present.",
        "",
    ]
    return "\n".join(out)


def section_audit(results: Path) -> str:
    d = _load(results / "text_blind_audit.json")
    if not d:
        return "## 2. Text-blind benchmark audit\n\n_Not yet run: `python scripts/text_blind_audit.py --roots ...`._\n"
    out = [
        "## 2. Text-blind benchmark audit",
        "",
        "Accuracy of a training-free 32×32 luminance + RGB-histogram matcher that **never reads "
        "the prompt**. Wilson 95% intervals.",
        "",
        "| task | n | chance | most-frequent-answer | image-match (text-blind) |",
        "|---|---|---|---|---|",
    ]
    for task, r in sorted(d.items()):
        pos = f"{r['position_acc']:.2f} [{r['position_ci'][0]:.2f}, {r['position_ci'][1]:.2f}]"
        mat = (
            f"**{r['match_acc']:.2f}** [{r['match_ci'][0]:.2f}, {r['match_ci'][1]:.2f}] (n={r['match_n']})"
            if "match_acc" in r
            else "n/a"
        )
        out.append(f"| {task} | {r['n_items']} | {r['chance']:.2f} | {pos} | {mat} |")
    out += [
        "",
        "Tasks with no query image to match against show `n/a`; the matcher is inapplicable, "
        "not merely unsuccessful.",
        "",
    ]
    return "\n".join(out)


def section_efficiency(results: Path) -> str:
    d = _load(results / "sim_efficiency.json")
    if not d:
        return "## 3. Scope condition\n\n_Not yet run: `python scripts/run_simulation.py efficiency`._\n"
    rows = d["rows"]
    sizes = sorted({r["corpus_size"] for r in rows})
    conds = list(dict.fromkeys(r["condition"] for r in rows))
    out = [
        "## 3. Sample efficiency — the contrastive setting",
        "",
        "Lexicon accuracy vs. finite corpus size, contrastive objective, on the corrected "
        "multi-exemplar world with held-out evaluation. An earlier version of this table was "
        "measured with a single appearance per object, where every condition saturated at "
        "1.000 and the comparison was vacuous; see METHOD.md §6.2b for the retraction.",
        "",
        "| condition | " + " | ".join(f"n={s}" for s in sizes) + " |",
        "|---|" + "---|" * len(sizes),
    ]
    for c in conds:
        cells = []
        for s in sizes:
            r = next((x for x in rows if x["condition"] == c and x["corpus_size"] == s), None)
            cells.append(f"{r['acc_mean']:.3f}" if r else "—")
        out.append(f"| {c} | " + " | ".join(cells) + " |")
    out.append("")
    out.append("Hub rate (same runs):")
    out.append("")
    out.append("| condition | " + " | ".join(f"n={s_}" for s_ in sizes) + " |")
    out.append("|---|" + "---|" * len(sizes))
    for c in conds:
        cells = []
        for s_ in sizes:
            r = next((x for x in rows if x["condition"] == c and x["corpus_size"] == s_), None)
            cells.append(f"{r['hub_mean']:.3f}" if r else "—")
        out.append(f"| {c} | " + " | ".join(cells) + " |")
    out += [
        "",
        "`hub` is the fraction of words whose nearest referent is a never-named background "
        "object — the quantity Proposition 2 predicts the column constraint should suppress.",
        "",
    ]
    return "\n".join(out)


def section_rho(results: Path) -> str:
    d = _load(results / "sim_rho.json")
    if not d:
        return "## 3b. Mutual-exclusivity strength\n\n_Not yet run: `python scripts/run_simulation.py rho`._\n"
    rows = d["rows"]

    def key(r):
        v = r["condition"].split("=", 1)[1]
        return float("inf") if v == "None" else float(v)

    rows = sorted(rows, key=key)
    labels = ["0 (row softmax)" if key(r) == 0 else ("∞ (balanced)" if key(r) == float("inf")
              else f"{key(r):g}") for r in rows]
    out = [
        "## 3b. Mutual-exclusivity strength ρ",
        "",
        f"Contrastive setting, corpus = {d['args'].get('corpus_size','?')} episodes, "
        f"{d['args'].get('seeds','?')} seeds. `ρ = 0` *is* region–word contrastive learning "
        "(Proposition 1), so this sweep interpolates continuously from the baseline.",
        "",
        "| ρ | " + " | ".join(labels) + " |",
        "|---|" + "---|" * len(rows),
        "| accuracy | " + " | ".join(f"{r['acc_mean']:.3f}" for r in rows) + " |",
        "| hub rate | " + " | ".join(f"{r['hub_mean']:.3f}" for r in rows) + " |",
        "",
        "The optimum is **interior**: full exclusivity over-constrains, because real scenes do "
        "contain several plausible referents. Hub rate falls between the endpoints (0.050 → "
        "0.025) but is not monotone in between and is noisy at this seed count.",
        "",
    ]
    return "\n".join(out)


def section_yusmith(results: Path) -> str:
    d = _load(results / "sim_yusmith.json")
    if not d:
        return "## 4. Yu & Smith (2007) psychometric fit\n\n_Not yet run: `python scripts/run_simulation.py yusmith`._\n"
    rows = d["rows"]
    best = min(rows, key=lambda r: r["rmse"])
    out = [
        "## 4. Yu & Smith (2007) psychometric fit",
        "",
        "An unconstrained ideal observer is at ceiling on the original design at *every* memory-decay "
        "rate, so forgetting is not the limit that explains human performance. Limited encoding is: "
        "a learner registers only a few of the word-object pairs on offer per trial.",
        "",
        "| objects encoded / trial | 2×2 | 3×3 | 4×4 | RMSE vs human |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        p = r["pred"]
        k = r.get("attend_k", r.get("gamma"))
        label = "unlimited" if k in (0, None) else str(k)
        out.append(
            f"| {label} | {p.get('2', float('nan')):.3f} | {p.get('3', float('nan')):.3f} | "
            f"{p.get('4', float('nan')):.3f} | {r['rmse']:.3f} |"
        )
    h = rows[0]["human"]
    out += [
        f"| **human** | {h['2']:.3f} | {h['3']:.3f} | {h['4']:.3f} | — |",
        "",
        f"Best fit: {best.get('attend_k', '?')} objects encoded per trial "
        f"(RMSE {best['rmse']:.3f}).",
        "",
    ]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--results", type=Path, default=Path("results"))
    ap.add_argument("--out", type=Path, default=Path("RESULTS.md"))
    args = ap.parse_args()
    text = "\n".join([
        HEADER,
        section_ar(args.results),
        section_audit(args.results),
        section_efficiency(args.results),
        section_rho(args.results),
        section_yusmith(args.results),
    ])
    args.out.write_text(text)
    print(f"wrote {args.out} ({len(text)} chars)")


if __name__ == "__main__":
    main()
